FROM gradle:7.4.2-jdk11-alpine AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon
#FROM openjdk:11-jdk-slim
FROM openjdk:11.0.14-jre
EXPOSE 8080
#RUN mkdir /app
COPY --from=build /home/gradle/src/build/libs/demo1-0.0.1-SNAPSHOT.jar /app.jar
ENTRYPOINT ["java","-jar","/app.jar"]